version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-dev
    ports:
      # FastAPI is running on port 8000 in the container. Make it accessible 
      # on port 8000 of the local machine
      - "8000:8000"
    
  # NOTE: Make sure the .env-dev matches all the connection
  # details that we listed here.
  postgres:
    image: postgres:15
    env_file:
      - .env-dev
    ports:
      - "5432:5432"

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042" # Default Cassandra port
    env_file:
      - .env-dev

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    env_file:
      - .env-dev